version: "2"
services:
    to-do:
        image: mhart/alpine-node:8.11.4
        environment:
            - NODE_ENV=development
        restart: always
        ports:
            - "3000:3000"
        working_dir: /to-do
        volumes:
            - ./to-do:/to-do
        entrypoint: ["npm", "start"]
        links:
            - api
        networks:
            ["webappnetwork"]
    api:
        image: node:8.11.4
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - ./api:/api
            - /api/node_modules

        networks:
            ["webappnetwork"]

networks:
    webappnetwork:
        driver: bridge
